default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: '123456'

development:
  <<: *default
  database: onebitcode_exchance_development

test:
  <<: *default
  database: onebitcode_exchance_test

production:
  <<: *default
  database: onebitcode_exchance_production