# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a32fc521901ba95f5af8babf523f91ff962fa4ee698f73c99d7e354e134bebab5ec729f78c5ff8c86f071d670c56c6741586d9d4a65dc191c40af192d4691f9

test:
  secret_key_base: 6057bc7a395a9e77407243c74c90a97cb81721edd46ccd806990ef93655bb4173fd0d84b2492178b2887d968c6ea0c96c1bf95aa5b04088efbdb7d1e15eb8c1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
